### ISSUE TITLE
Provide master-slave states

### ISSUE THREAD

**Issue by bersace** [saltstack-formulas/jenkins-formula#15]
Hi,

Here at [PeopleDoc](http://www.people-doc.com/) we built a salt formula for deploying master/slave jenkins. Our target is to fully provision jenkins through salt. We open sourced the code at https://github.com/novafloss/ci-formula . What do you thing of merging ci-formula in jenkins-formula to address more use case.

In the end we would have `jenkins.master` and `jenkins.slave` entry point. We could also add `jenkins_job`, `jenkins_view` and `jenkins_plugin` states, but this require `jenkins-cli`.

If you are ok, i can do some pull requests to progressively merge interesting feature in official jenkins-formula.

Regards,
Étienne

**Comment by puneetk** [comment]
> If you are ok, i can do some pull requests to progressively merge interesting feature in official jenkins-formula. 
@bersace yes please

**Comment by bersace** [comment]
Thanks :-)

**Comment by myoung34** [comment]
What do you need out of this? To be a 'slave' you just need `java` and the jarfile from the master.
See https://wiki.jenkins-ci.org/display/JENKINS/Step+by+step+guide+to+set+up+master+and+slave+machines

If anything this should be a new formula, there's not a lot of overlap, not enough to consider splitting this into multiple roles. They'd be wildly different

**Comment by bersace** [comment]
Hi we shifted to Ansible and are happy with this. Thanks for the feedback !

https://github.com/novafloss/ansible-role-jenkins-node
