### ISSUE TITLE
Allow setting server name

### ISSUE THREAD

**Issue by jpic** [saltstack-formulas/jenkins-formula#21]
Currently, the [server_name](https://github.com/saltstack-formulas/jenkins-formula/blob/master/jenkins/files/nginx.conf#L10) nginx configuration variable for jenkins is commented.

It would be great if we could override it, so that other sites can live along with jenkins on this nginx configuration.

**Comment by puneetk** [comment]
send over a pull request, sounds like a good change.

**Comment by jpic** [comment]
I would love to discuss requirements and design before issuing a pull request:

- how should the grain and pillar structure look like ?
- how should it be used in the template ?

**Comment by puneetk** [comment]
in the map.jinja you can add a server_name key, similar to the port key that is there. Then use it as {{ jenkins.server_name }} in the nginx.conf similar to the {{ jenkins.port }} usage. 
Also add the key to the pillar.example file
