### ISSUE TITLE
for CentOS you need java to be installed 

### ISSUE THREAD

**Issue by jmdcal** [saltstack-formulas/jenkins-formula#29]
Currently the formula does not work for cent7, because java needs to be installed.
See https://github.com/saltstack-formulas/jenkins-formula/pull/27 for some solutions.

**Comment by myoung34** [comment]
This doesnt need to be in the jenkins formula, you can [use the java formula](https://github.com/saltstack-formulas/java-formula) or [the sun java formula](https://github.com/saltstack-formulas/sun-java-formula) before applying any jenkins states.
