### ISSUE TITLE
Plugins won't install if security is enabled on jenkins

### ISSUE THREAD

**Issue by scheibinger** [saltstack-formulas/jenkins-formula#44]
There should be a way of providing jenkins credentials in order to use jenkins-cli. Jenkins-cli uses rest calls to install plugins. `jenkins.plugins` state will basically break as soon as you setup security on jenkins.

e.g. I would like to use jenkins github oauth plugin for authentication: https://wiki.jenkins-ci.org/display/JENKINS/Github+OAuth+Plugin

There should be a way of passing github oauth token for connections between jenkins-cli and local jenkins instance. All credentials should be provided in pillar.

**Comment by gravyboat** [comment]
This is a good idea! If you want to prep a PR for it I would be happy to merge it in.

**Comment by myoung34** [comment]
@scheibinger I also would merge it if you came up with functionality.
If you look at the latest code I already added some code to support authentication (Jenkins V2 uses a secrets file), you could modify that to try to use a provided user/pass in pillar form before attempting it.

**Comment by myoung34** [comment]
closing after a year of inactivity. Please re-open if issue is still relevant
