### ISSUE TITLE
Unable to install plugins with default debian config

### ISSUE THREAD

**Issue by dosercz** [saltstack-formulas/jenkins-formula#46]
I have tried to install plugins with default config.xml file on debian 8, but jenkins cli doesn't work due to error: No X-Jenkins-CLI2-Port among.
I have fix it in config.xml - changed value from default `<slaveAgentPort>-1</slaveAgentPort>` to 0 (random port) a restart jenkins service before `jenkins_listening`
Tested on jenkins version 2.7/2.8 instaled by this formula.
Does someone have same problem with plugins/cli or some better solution?

**Comment by gravyboat** [comment]
Hmm, is this due to Jenkins trying to connect to the wrong port to install the plugin? I haven't seen this error reported before.

**Comment by dosercz** [comment]
No, value -1 means disabled TCP port for JNLP agents. So, problem is not wrong port, but it is disabled.

**Comment by gravyboat** [comment]
Right now we don't manage the config.xml. If you want a propose a PR that pulls from the pillar and such to do so I would be happy to review it.

**Comment by dosercz** [comment]
I know, but without change in config.xml formula for plugins doesn't work for me. That's the reason, why I have created issue.

**Comment by gravyboat** [comment]
I guess I'm confused, is your config.xml managed from a different formula? If not I'm happy to review a PR that adds support for managing the config.xml.

**Comment by dosercz** [comment]
No, I have default config.xml from package installed with:
```
include:
  - jenkins
  - jenkins.plugins
```

**Comment by gravyboat** [comment]
Right, so what I'm saying is if you wanted to modify the `config.xml` and handle templating it via the jenkins.plugins state then we could review a PR to do so. Past that (since we don't manage the config file) there isn't much we can do to address this.

**Comment by shuang83** [comment]
Ran into the same issue and instead of managing config.xml, we added an entry to manage /etc/default/jenkins (or /etc/sysconfig/jenkins for RH) to append "-Djenkins.model.Jenkins.slaveAgentPort=0" to JAVA_ARGS (or JENKINS_JAVA_OPTIONS for RH)

**Comment by myoung34** [comment]
I'm not sure if this is directly resolved in Debian but plugins work in CentOS/AWS Linux as of the latest commits. Reopen if it is still an issue
