### ISSUE TITLE
Put all macros in a different file and import them as needed

### ISSUE THREAD

**Issue by byteknacker** [saltstack-formulas/jenkins-formula#50]
Just a slight suggestion and I also wish to ask for your opinion about this:

There are a number of macros in the sls files. How about we put them into a single file called macros and comment each macros what it does. Then import them with a single line into any states files if they are needed.

A better approach may yet be to separate the macro files based on topic:

macro-cli
macro-jenkins
macro-etc...

This way the user knows exactly which macro is written in which file and if someone just need to update one, they can do so without messing around with the other files.

This will, however, only add more benefit if this project becomes larger and we have more macros to maintain. To make it future proof, I do suggest we start now with this.

**Comment by gravyboat** [comment]
Should probably ask @blast-hardcheese, my familiarity with this formula is pretty minimal.

**Comment by byteknacker** [comment]
Would you mind taking a look at the log of my Travis builds? I cannot get it passed for some reason and it gets stuck at the authorisation with the Jenkins CLI.

**Comment by byteknacker** [comment]
@blast-hardcheese What do you think of this idea of putting all macros in a separate folder structure. At least put them into one file.

**Comment by gravyboat** [comment]
Sorry but I don't have time to look at Travis build logs currently. I don't get paid to maintain these repos at all so I have to limit my time doing formula work.

**Comment by byteknacker** [comment]
Ok of course no worries!

**Comment by myoung34** [comment]
I can reopen this if a PR gets submitted to add the functionality.
