### ISSUE TITLE
Question: Reason for Jinja import after YAML include

### ISSUE THREAD

**Issue by byteknacker** [saltstack-formulas/jenkins-formula#53]
Just curious if it makes any difference to put the jinja imports before the YAML include found in jobs.sls for example.

What is the best practice if if it does not make a difference, which one should we stick to?

**Comment by gravyboat** [comment]
Doesn't really matter, usually the jinja stuff will go first.

**Comment by byteknacker** [comment]
Ok, do you prefer if I make the jinja import at the top always before include since this would either overwrite or conflict with your current files, at least two or three.

**Comment by gravyboat** [comment]
I would say stick with whatever the existing structure is from the repo, so go with what wins 2/3 times.

**Comment by byteknacker** [comment]
Ok will do
