### ISSUE TITLE
installing jenkins.cli fails (for jenkins 2.16 on Ubuntu 14.04)

### ISSUE THREAD

**Issue by colegatron** [saltstack-formulas/jenkins-formula#55]
After running jenkins state and then running jenkins.cli, on state jenkins_responding the java call fails with a 403.

Reproducing it:
$ sudo java -jar /var/cache/jenkins/jenkins-cli.jar -s http://localhost:8080

java.io.IOException: No X-Jenkins-CLI2-Port among [X-Jenkins, null, Server, X-Content-Type-Options, X-You-Are-In-Group, X-Hudson, Date, X-Jenkins-Session, X-You-Are-Authenticated-As, X-Required-Permission, Set-Cookie, Expires, Content-Length, Content-Type]
    at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
    at hudson.cli.CLI.<init>(CLI.java:128)
    at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
    at hudson.cli.CLI._main(CLI.java:473)
    at hudson.cli.CLI.main(CLI.java:384)
    Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli

**Comment by byteknacker** [comment]
Can you login on the web ui? If so, try to set the TCP security to random, then try to use the cli in the terminal again. If the TCP is disabled, I think you cannot use the cli, not even for login.

**Comment by colegatron** [comment]
You are right.
The webui, at least the current version of Jenkins, is by default disabled.
You have to write a random password stored
at /var/lib/jenkins/secrets/initialAdminPassword to access the webui.

Then, and only then you can enable the "TCP port for JNLP" clients and
therefore install the jenkins.cli state.

I tried to find the configuration element on the /var/lib/jenkins files to
automate its enable it to install cli, but not found where it is configured.






--

*Iván González Valiente*

Systems Developer / AWS Certified Developer






2016-08-28 10:32 GMT+02:00 Xiangyu Johannes Wu <notifications@github.com>:

**Comment by byteknacker** [comment]
It is configured in the config.xml file in /var/lib/jenkins. I made a git repo out of a completely blank jenkins setup where you can just use that to login, since I changed the TCP access manually and then stored the config in this repo: 

[Blank Jenkins Config ](https://github.com/byteknacker/blank-jenkins-config)

You just need to replace your existing /var/lib/jenkins with this configuration repo.

**Comment by myoung34** [comment]
Fixed in latest version of `master`
