### ISSUE TITLE
Provide platform-specific default settings

### ISSUE THREAD

**Issue by sroegner** [saltstack-formulas/jenkins-formula#70]
This for now is mainly to resolve the netcat-related issues that have come up around #47 - as netcat (the package) is named differently and (the binary) has different flags it looks like a good solution to me to add platform-specific settings to map.jinja - i'll follow up with a PR asap.

**Comment by myoung34** [comment]
This is resolved by #69 , correct?

**Comment by sroegner** [comment]
Correct, both commits have to go together

**Comment by sroegner** [comment]
Fixed with PR #69
